### ISSUE TITLE
Press clippings - exhibition layout

### ISSUE THREAD

**Issue by robertocarroll** [robertocarroll/barjeel#49]
After discussion, we're going to replace the featured (in the right column) with press clippings. 

I will check how the featured is set up, remove the limit so it shows all articles and rename it so it makes sense as press clippings.

**Comment by clintmclean** [comment]
Ok so remember we had two options we were proposing to them:
1. Put press clippings in the far right column and give them each a thumbnail/preview image so we'd have one square or ten squares down the right hand side
2. Just a link at the bottom of the text with a small icon and name of the article.

They opted for number two. So we need a little icon that goes before the link name - maybe something only twice as large as the text. I think if we have five press clippings for an article, we should show all five as links so my icon designs I just sent you don't really work.

**Comment by robertocarroll** [comment]
OK. Thanks for the refresher. Sounds straightforward enough. Needs something simple - it can't really have text or numbers in can it? They won't be legible at that size ...

Does it even need an icon at all? We don't use icons in this way in other parts of the site do we?

**Comment by clintmclean** [comment]
Maybe it could just be a bullseye with our barjeel colours or something. I think it helps if it isn't just a link, or if the link is on a background or something to treat it with respect.
...but yeah, definitely not the logos I just sent!

**Comment by robertocarroll** [comment]
I think you're right that it needs something to indicate that the user is leaving the site. 

Here's the external link icon from gov.uk as an example:
https://github.com/alphagov/govuk_frontend_toolkit/blob/master/images/external-links/external-link-black-24x24.png

**Comment by clintmclean** [comment]
I'm totally messing things up bouncing back and forth between github and slack.

I don't think inconsistency is a problem here - we havent' done it previously because nothing called for it. I think this is a good usage of it. For a while we were just sticking new content on - to me this feels like we're designing it into place.

**Comment by robertocarroll** [comment]
Perhaps you could outline how this case is different than a link to pdf ... or to another website ... I'm not quite clear - is it the fact that it is a link to a news article that you are trying to convey using the icon? That seems a bit odd and something better catered for with the module title etc.

**Comment by clintmclean** [comment]
It is a way to treat the press articles special as a unit. We treated the downloads which are pdfs special, just in a different way. It doesn't mean every pdf on the site should be treated like them, but everything in the download section should be.
The press icon will let us visually signal the viewer that it is a press article regardless of where they see it since it could be in News or in Exhibitions etc.

**Comment by robertocarroll** [comment]
I'm still not convinced about suddenly using an icon to mark out a type of content which isn't commonly established, eg video, external link, pdf, etc, when we haven't used it elsewhere on the site, but ultimately it's a design thing if you think it best to start using them now ...

**Comment by clintmclean** [comment]
I guess I am looking at the Press more as content than links. Though they would be in the form of links, some would be taking the reader to content within the site so in that respect they are much like the thumbnails used to take readers to content. Some of them take readers to the content which is outside of the site but all Press should be treated the visually the same so I don't really see designing the links in some way (whether with icons or on backgrounds or buttons or whatever) as going crazy with inconsistency. We haven't done it before because there wasn't a reason that fit.

The other thing is that when we had our three way skype, we came up with two solutions and I was to pitch them both to barjeel and see what they thought. The preferred the link version so to go back to them now and say we don't like it just seems unnecessary to me.

**Comment by robertocarroll** [comment]
I'm only pointing out what seems to me to be an issue with the use of icons in this way. Perhaps I misunderstood / am misunderstanding what's being suggested. I didn't realise that icons in this format were an intrinsic part of the proposal we were putting to the client for this new section.

Anyway, this all feels a bit hypothetical (and therefore a bit wasteful). If you have a solution which you and the client are happy with and you think will benefit users then I don't mean to stand in the way.

**Comment by clintmclean** [comment]
Una has made icons which we can put with links at the bottom of the exhibition page which relates to the press clipping. In the event it is a pdf of press clipping, we will upload it to the barjeel media library and link it from there.
To add in the icon... probably a 'font icon' is the best way to do it right? So we can add it in line directly as we add the link? ...i didn't have very good luck when i tried to make an icon font but will try again.

**Comment by clintmclean** [comment]
I've made an icon font from Una's icon - I think. These are the instructions I used. http://www.webdesignerdepot.com/2013/04/how-to-turn-your-icons-into-a-web-font/
We need to add the CSS to our style sheet and host the fonts (i have also installed them on my computer). Can you look into that? The idea is I can type a code and have the icon appear.
Here's the zip of the files and demos.
[icomoon67847.zip](https://github.com/robertocarroll/barjeel/files/117769/icomoon67847.zip)

**Comment by robertocarroll** [comment]
Please could you add in the latest layout/design for this section. I can't seem to find it anywhere. (I realise the icon will be part of our icon overhaul in #51 )

**Comment by clintmclean** [comment]
At the bottom of the exhibition text - for example here: http://www.barjeelartfoundation.org/exhibitions/re-orient/

**Comment by robertocarroll** [comment]
So that's it with the icon in front? That's fine except for the new window. It's fairly accepted that a new window is bad for accessibility and for mobile users and for generally being polite: 

Reference: http://www.currybet.net/cbet_blog/2012/08/never-open-external-links-in-new-windows.php

Also, is there a reason you've included the url instead of the title? 
> [When writing a link, make it descriptive and front-load it with relevant terms instead of using something generic](https://www.gov.uk/guidance/content-design/links)

**Comment by robertocarroll** [comment]
To add an icon use: 

`<span class="icon icon-24 press-1 inline-icon"></span>`

there's press-1, press-2 and press-3 and there's icon-12, icon-24, icon-48, icon-72 and icon-96.
