### ISSUE TITLE
footer style

### ISSUE THREAD

**Issue by clintmclean** [robertocarroll/barjeel#55]
Can we style the footer a little bit it looks like things moved when we removed the original three icons from below the barjeel address. Can we tidy up a little something like this:

1. Lets align the search bar to the bottom of the social icons so they all sit on the same baseline. If it can be a few pixels higher it will visually look the same (circles look like they sit higher because of the narrow base)
2.I am also attaching new Search icons (normal and hover states) so we can style the search box to match (the black is 90% if you want to outline the search box itself). Can it have the same spacing between the search box and the icons as the icons have between each other? (diagram attached). Maybe that means the search box would get a little shorter if necessary.
3. Bring the barjeel logo and address back down so the top of the logo aligns with the top of the twitter boxes.
4. The social icons seem to have padding on the left of the Facebook but not on the right of the Instagram. Looks like Instagram aligns flush with the twitter box below whereas the other icons are all inset a little. Can you look into that?
<img width="1305" alt="screen shot 2016-02-22 at 13 12 18" src="https://cloud.githubusercontent.com/assets/4203246/13217872/f5c81290-d965-11e5-8473-7c3c03b3ea51.png">
[search svgs.zip](https://github.com/robertocarroll/barjeel/files/140537/search.svgs.zip)

**Comment by robertocarroll** [comment]
I've been meaning to ask: 

Would Barjeel be open to removing the Twitter widgets? They really do slow the site down and they end up loading megabytes of images. And they are on every page, so removing them would have a positive effect on the feel and performance of the site.

**Comment by clintmclean** [comment]
Hi - yeah I think this was a discussion when we did the site - I know you weren't in favour of including twitter and I realise they are a bit of a performance issue, but I think it would be a tough argument to get them to remove them - especially when they don't see the performance issue. Maybe it is about timing - if we can get him to agree to us doing his website we could move his to that site and these ones could disappear? ...though maybe that just moves the problem rather than fixing it...

**Comment by robertocarroll** [comment]
For Sultan's site it won't be a problem because we will be creating custom views from his data and feeds. 

For Barjeel, it's quite a serious issue. I tried a few weeks ago and because of what was in the Twitter feeds it added an extra 1MB to the page. At the moment it's not too bad because there aren't many images in there, but you can still see how we're loading our site nice and quick with as few requests as possible and then the Twitter thing goes off and does **a load more stuff** sending the page load from 3 seconds up to 13 seconds (see from 43 onwards) but more importantly adding stuff that will eat into a user's bandwidth on any device or connection (something you know all about!):

![fireshot capture 27 - webpagetest test_ - http___www webpagetest org_result_160304_e9_n3t_1_details_](https://cloud.githubusercontent.com/assets/1565953/13526945/6517c352-e203-11e5-8762-2cd2d668eb24.jpg)

**Comment by clintmclean** [comment]
ok so how about we make a good push to do his site and we try convince them to move his twitter to his new site and remove the other two?

**Comment by robertocarroll** [comment]
Sounds good.

**Comment by robertocarroll** [comment]
- I can't seem to find the new search icon and hover. Please could you re-send. 
- I'm not clear about the search box hover. Do you mean make it black on focus instead of red? 
- I've done the vertical alignments but the width ones are trickier. At the moment all icons are displayed flex with even spacing. I'd have to put the icons in groups of two in each grid column and then display flex and I still wouldn't be able to match up the search box distance with the icon distance because it would depend on screen size. It's quite a lot of work. Take a look at the moment and let me know.

**Comment by clintmclean** [comment]
Hi - search icons attached here.
With regards to the black, I just wondered if we should outline the search box in the same black (90%) that the icons are outlined in. ...maybe just white looks better since we have the search icon already outlined. I don't know - just wondering.

The vertical alignment is unfortunate - it really does stand out. I guess there is no way to align by moving or enlarging the twitter boxes rather than the icons? just thinking out loud...

C.
[search svgs and pngs.zip](https://github.com/robertocarroll/barjeel/files/173913/search.svgs.and.pngs.zip)
